name: Github Pages Deploy

on:
  push:
    branches:
      -"master"

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version:[15.x]
    
    steps:
      - name: Checkout
        user: actions/checkout@vl

      - name: Install and build
        run: npm Install && npm run build 

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.